### ISSUE TITLE
Mentioning the registering of the adapter

### ISSUE THREAD

**Issue by eheiberg** [dleavitt/faraday-typhoeus#4]
Hey there! Lovely adapter. Thank you so much!

I believe Faraday requires you to register the adapter before you can perform some of the examples in the README. 
As example: 

```ruby
conn = Faraday.new(...) do |f|
  f.adapter :typhoeus
end
```

Was giving me a 

```
     Faraday::Error:
       :typhoeus is not registered on Faraday::Adapter
```

Prior to me registering the adapter. Other users more familiar with Faraday might already know this, but I think it would be helpful if it were in the readme. 

As example, something in an initializer of some sort would have something like this:
```ruby
require 'faraday/adapter/typhoeus`

Faraday::Adapter.register_middleware(typhoeus: Faraday::Adapter::Typhoeus)

# Uncomment if you want to use typhoeus as your default adapter
# Faraday.default_adapter = :typhoeus
```

Thanks again!

**Comment by jethrodaniel** [comment]
The adapter is actually already registered here: https://github.com/dleavitt/faraday-typhoeus/blob/a198220261c671eb15c3611933de9a20269c90d2/lib/faraday/typhoeus.rb#L6-L12

You just need to `require 'faraday/typhoeus'` in order for it to be loaded. (which is missing from the README, fwiw).

**Comment by eheiberg** [comment]
OH THANK YOU! This is very helpful!
