### ISSUE TITLE
Issues with gzip adapter in combination with typhoeus

### ISSUE THREAD

**Issue by MathijsK93** [dleavitt/faraday-typhoeus#8]
We recently migrated our application from Faraday 1.x to 2.x and experiencing a problem with this adapter together with the [faraday-gzip](https://github.com/bodrovis/faraday-gzip) middleware. So the `Accept-Encoding` header is passed, but we no longer receive gzipped content as response. 

When I replace the `faraday-typhoeus` adapter with the following gist (copied from https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/adapters/faraday.rb):
https://gist.github.com/MathijsK93/d4ce59899d06c8da5d7ccc8a92868aea  it is working again.

So it looks like there's an issue in processing the response.

I also setup a repository to show the behaviour: https://github.com/payt/faraday_test
Branches:
`main` - Faraday 2, not working (`not in gzip format (Zlib::GzipFile::Error)`)
`faraday-1` - Faraday 1, working with faraday middleware gem + typhoeus adapter from typhoeus library itself

You can test it by:

```ruby
rails console
```

```ruby
GzipRequest.new.call
```

Maybe it's also an issue in the faraday-gzip gem, but because replacing the typhoeus adapter helped to solve the problem, I think the problem exists in this gem.

Please let me know if you need more information.

**Comment by dleavitt** [comment]
Thanks for the report and reproduction! I'll take a look shortly.

**Comment by dleavitt** [comment]
Hi @MathijsK93,

You shouldn't need to use middleware like faraday-gzip with this adapter - it supports "transparent" compression: https://github.com/dleavitt/faraday-typhoeus/commit/48bcbed903d79323ac00a4f730a75ea4eb0fd96c

In your repro example, try removing the gzip middleware and then running the request - you should still see `"content-encoding"=>"gzip"` in the response headers. By default, the adapter tells libcurl to [automatically populate](https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html) the outgoing "Accept" header with its supported encodings and then decompress the response before sending it through to Ruby.

If you want to opt out of this behavior, you can do something like this:

```ruby
require 'faraday'
require 'faraday/typhoeus'
require 'faraday/gzip'
require 'stringio'
require 'irb'

conn = Faraday.new(url: 'https://date.nager.at/api/v3') do |faraday|
  # turn off libcurl encoding handling
  faraday.adapter :typhoeus, accept_encoding: nil
  faraday.request :json
  faraday.response :json
  faraday.request :gzip
end

r = conn.get('PublicHolidays/2023/AT')
```

**Comment by MathijsK93** [comment]
@dleavitt thank you very much for your reply. I will test it out!
